import type { Metadata } from 'next'
import { Geist, Geist_Mono } from 'next/font/google'
import { NextIntlClientProvider } from 'next-intl'
import '../globals.css'
import { ThemeProvider } from '../components/theme-provider'
import { ThemeSwitcher } from '../components/theme-switcher'
import { LocaleSwitcher } from '../components/locale_switcher'
const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
  params,
}: Readonly<{
  children: React.ReactNode
  params: Promise<{ locale: string }>
}>) {
  const { locale } = await params
  return (
    <html lang={locale} suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased `}
      >
        <NextIntlClientProvider>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <header>
              <div className="flex flex-row justify-between container mx-auto">
                <div>DoDo</div>
                <div className="flex flex-row gap-4">
                  <div>
                    <ThemeSwitcher />
                  </div>
                  <div>
                    <LocaleSwitcher />
                  </div>
                </div>
              </div>
            </header>
            <main className=""> {children}</main>
            <footer className="container mx-auto">footer</footer>
          </ThemeProvider>
        </NextIntlClientProvider>
      </body>
    </html>
  )
}
